# Generated by Django 4.0.1 on 2022-01-06 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0003_advertisement_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='draft',
        ),
    ]
